
<div id="positionHolder" style="min-width:600px; width:90%;height:250px; padding-top:50px; margin-bottom:50px;"></div>

<script>
    $( document ).ready(function() {
        //reference to db
        var myFirebaseRef = new Firebase("https://lora.firebaseio.com/");

        // prepare points data
        var PointsX = [0];
        var PointsY = [0];

        //fetch all sensors data by type RobotPosition
        /**
         * @note orderByChild - fetching all data that has column Type
         * @note startAt & endAt - equivalent of where
         * @note limitToLast - we limit the last 100 results (If you don't have any document you might have issue)
         */
        myFirebaseRef.child("firebase/lora").orderByChild('Type')
            .startAt('RobotPosition').endAt('RobotPosition').limitToLast(100)
            .on('value', function(snapshot) {
                console.log(snapshot.val());

                $.each(snapshot.val(), function( index, value ) {
                    //getting point X value
                    var x = value.Position.Point.X;
                    //getting point Y value
                    var y = value.Position.Point.Y;
                    //adding data to array
                    PointsX.push(x);
                    PointsY.push(y);

                });

                var positionHolder = document.getElementById('positionHolder');
                //we are using plotly
                Plotly.plot( positionHolder, [{
                    x: PointsX,
                    y: PointsY
                }], { yaxis: { title: "Y values" }, xaxis: { title: "X values" }, margin: { t: 0 } } );
        });

    });
</script>
